### ISSUE TITLE
Adding existing features to refhost test pack

### ISSUE THREAD

**Issue by 0rnela** [SUSE/spacewalk-testsuite-base#125]
Can the following features please be added to the pack, to cover those smoke tests that we have tests for? 

-  mgr_create_bootstrap_repo.feature
- register_client.feature
- salt_minion_details.feature
- salt_minions_page.feature
-  test_reboot.feature
- systems_needing_reboot.feature
-  salt_install_package.feature
-  salt_remote_cmds.feature
-  salt_action_pickedup.feature
- lock_packages_on_client.feature

**Comment by MalloZup** [comment]
thx @0rnela , 
salt_action_pickedup is not even working for the normal testsuite,  atm

 the rest could be added. we need to test if the feature are taking other depend. from other feature.

**Comment by MalloZup** [comment]
- [ ] mgr_create_bootstrap_repo.feature
- [ ] register_client.feature
- [x] salt_minion_details.feature
- [x] salt_minions_page.feature
- [ ] test_reboot.feature
- [ ] systems_needing_reboot.feature
- [ ] salt_install_package.feature
- [x] salt_remote_cmds.feature
- [x] salt_action_pickedup.feature
- [ ] lock_packages_on_client.feature

**Comment by MalloZup** [comment]
Bootstrap repo is disabled too...

**Comment by MalloZup** [comment]
fixed for refhost 30. head need rework, closing for moment.
