### ISSUE TITLE
Improve Rakefile and find better alternative to yaml

### ISSUE THREAD

**Issue by MalloZup** [SUSE/spacewalk-testsuite-base#204]

**Comment by MalloZup** [comment]
Remove useless Task in Rakefile
Improve yaml , find an alternative to yaml.

**Comment by Bischoff** [comment]
Agree on the cleanup part.

About the yaml files in run_sets/, well, they are just a lists of features with a mechanism to comment out lines. About any text format would do. However, I don't see why yaml is bad.

Or were you thinking at other yaml files?
