### ISSUE TITLE
Replace "I wait for XX sec" with proper functions

### ISSUE THREAD

**Issue by MalloZup** [SUSE/spacewalk-testsuite-base#211]
This step  sleep function means:
1) Performance and lack of real fonctions check
2) the possibility of failures issue because the sleep is not enoug

 When possible substitute sleep with real fonctions

**Comment by MalloZup** [comment]
- [ ] features/centos_salt_remote_cmds.feature:16:    And I wait for "5" seconds
- [ ] features/centos_salt_remote_cmds.feature:19:    And I wait for "15" seconds
- [ ] features/salt_action_pickedup.feature:27:    And I wait for "1" seconds
- [ ] features/salt_action_pickedup.feature:31:    And I wait for "6" seconds  
- [ ] features/minion_bootstrap.feature:18:     And I wait for "100" seconds
- [ ] features/minion_bootstrap.feature:37:    Then I wait for "3" seconds
- [ ] features/minion_bootstrap.feature:80:     And I wait for "100" seconds
- [ ] features/minion_bootstrap.feature:118:     And I wait for "5" seconds
- [ ] features/minion_bootstrap.feature:141:     And I wait for "15" seconds
- [ ] features/minion_bootstrap.feature:156:     And I wait for "15" seconds
- [ ] features/minion_bootstrap.feature:171:     And I wait for "15" seconds
- [ ] features/minion_bootstrap.feature:185:     And I wait for "30" seconds
- [ ] features/cve_audit.feature:19:    And I wait for "5" seconds
- [ ] features/init_user_create.feature:56:    Then I wait for mgr-sync refresh is finished
- [ ] features/migrate_client_to_minion.feature:20:     And I wait for "100" seconds
- [ ] features/migrate_client_to_minion.feature:54:     And I wait for "5" seconds
- [ ] features/minion_centos_bootstrap.feature:17:     And I wait for "150" seconds
- [ ] features/powermanagement.feature:37:    And I wait for "20" seconds
- [ ] features/salt_ssh.feature:25:    And I wait for "15" seconds
- [ ] features/salt_ssh.feature:27:    And I wait for "10" seconds
- [ ] features/salt_ssh.feature:54:    Then I wait for "15" seconds
- [ ] features/salt_ssh.feature:72:    And I wait for "60" seconds
- [ ] features/salt_ssh.feature:84:    And I wait for "100" seconds
- [ ] features/salt_ssh.feature:105:    And I wait for "15" seconds
- [ ] features/salt_ssh.feature:107:    And I wait for "10" seconds
- [ ] features/salt_ssh.feature:134:    Then I wait for "15" seconds
- [ ] features/salt_ssh.feature:152:    And I wait for "60" seconds
- [ ] features/salt_ssh.feature:173:    And I wait for "100" seconds
- [ ] features/salt_install_package.feature:16:    And I wait for "5" seconds
- [ ] features/salt_minions_page.feature:41:    And I wait for "20" seconds
- [ ] features/salt_regression_multiminion.feature:22:    And I wait for "50" seconds
- [ ] features/salt_regression_multiminion.feature:32:    Then I wait for "3" seconds
- [ ] features/salt_remote_cmds.feature:18:    Then I wait for "3" seconds
- [ ] features/setup_wizard.feature:35:    And I wait for "20" seconds
- [ ] features/xmlrpc_VHM.feature:49:    And I wait for "10" seconds
- [ ] features/xmlrpc_cve_audit.feature:13:    And I wait for "10" seconds
- [ ] features/xmlrpc_cve_audit.feature:30:    And I wait for "5" seconds
- [ ] features/centos_salt_ssh.feature:30:    And I wait for "15" seconds
- [ ] features/centos_salt_ssh.feature:32:    And I wait for "10" seconds
- [ ] features/centos_salt_ssh.feature:55:    Then I wait for "15" seconds
- [ ] features/centos_salt_ssh.feature:69:    And I wait for "60" seconds
- [ ] features/centos_salt_ssh.feature:81:    And I wait for "60" seconds
- [ ] features/centos_salt_ssh.feature:102:    And I wait for "15" seconds
- [ ] features/centos_salt_ssh.feature:104:    And I wait for "10" seconds
- [ ] features/centos_salt_ssh.feature:127:    Then I wait for "15" seconds
- [ ] features/centos_salt_ssh.feature:141:    And I wait for "60" seconds
- [ ] features/centos_salt_ssh.feature:158:    And I wait for "60" seconds
- [ ] features/baremetal_test.feature:76:    And I wait for "30" seconds

**Comment by Bischoff** [comment]
Yes this is most needed. As a beginning, we should refrain from using "I wait" as much as we can.

(but I think it's not good having a list of check boxes here. Trello cards have items list and they are our normal way to track our progress)

**Comment by MalloZup** [comment]
The testsuite is an open source project, is not a private project repo. Trello is not open. Anyone ho want to contribuite could solve this , in trello not.

**Comment by MalloZup** [comment]
i close this because it's a part of another
