### ISSUE TITLE
Reorder, reduce simplify structure of Features dependencies

### ISSUE THREAD

**Issue by MalloZup** [SUSE/spacewalk-testsuite-base#223]
We want to know wich Features depends from others Feature.
To accomplish this, we need to create graphs that show this clearly.

**Comment by MalloZup** [comment]
Technically this can be done with yaml files, Rakefile​ Tasks. Wach yaml File contains feauees seta. Rakefile Will orchestrate the execution order.

Additionaly we could draw a three od sets dependencies.

**Comment by Bischoff** [comment]
Yes, we need to split the test suite, and basing it on Rakefiles just makes sense. +1.

How would you determine the sets? "Based on my experience" is a valid answer ;-) or do you envision using a tool that could give us a graph we could use as a base?

**Comment by MalloZup** [comment]
this will be adressed too soon by idempotent, closing
