### ISSUE TITLE
features not yet automated [BACKLOG]

### ISSUE THREAD

**Issue by MalloZup** [SUSE/spacewalk-testsuite-base#225]
## NEW: NEED PRIOTIZATION
(Add here feature that you are not sure which prio need to be set)

- CentOS 7 Spacewalk Features – Software Crashes  ( should we/suse-mgr test that?

## HIGH
- proxy (Whole feature is missing) 
- visualization (whole feature is missing)
-  [salt-ssh] Minion: test that  run.cmd, pkg install, and patch install are ok
- trad-client centos7: test patch installation
- minion centos7 : test patch installation

## MEDIUM
- search a system based on its location (country, state/province and city)
- system groups ( we have only a test for creating a group)
- bootstrap script with option "bootstrap with salt"
- salt formulas on SSH minion
- reschedule failed state/highstate 
- Schedule highstate apply for multiples systems with SSM: `System group > States > Highstate`
  -> tests if minion one of the minions is down, test with other minions up

## LOW
- System Set Manager : better coverage
- Test Inspect status and Reinspect button & dialog in image overview page

## technical debt: 
( this test are not maintenable in current status, take to much time, make the whole testsuite instable more difficult to debug.)
- migrate a traditional client in SSH push mode into a salt minion
- migrate a RHEL traditional client into a salt minion, and make sure rhnplugin is disabled
- migrate from a service pack to the other with synchronized repos (SALT minion)
- migrate from a service pack to the other with synchronized repos (traditional client)
- migration tests : better coverage (more minion types - 1. trad>salt (implemented), 2. trad>salt-ssh-push,

**Comment by Bischoff** [comment]
I can see above a link, but that doesn't tell me what the issue is, and once this is defined, why we should do that.

**Comment by Bischoff** [comment]
Also, I don't understand the title of this issue. What is it about ?

**Comment by MalloZup** [comment]
@Bischoff i was thinking that we conserve this issue, but maybe for future  we just add an issue for every feature we need to do ( assuming this becomes not to big)

**Comment by Bischoff** [comment]
Personally, I prefer having a single list, there is more visibility.

It would even be better with a list in git, so we have history.

I'm not too found of these nifty web tools. I find this "issues" tool confused.

**Comment by MalloZup** [comment]
@Bischoff ok, then we stay with one big-list.

**Comment by MalloZup** [comment]
i added here like 10 peoples that are from all mixed team, gui, salt, etc, (git limited to 10), so you can assign/view/review/ the list

**Comment by kkaempf** [comment]
This list belongs to the test document, not to this repo. The test document defines areas of testing, urgency of testing, and manual vs. automated.

**Comment by Bischoff** [comment]
@kkaempf which test document?

If you refer to the test plan, it is a high view document, improper for day-to-day reviews, progress of manual tests and details of automation.

I'll copy this list to gitlab's galaxy/galaxy-test-review where similar everyday tracking information already resides.

**Comment by MalloZup** [comment]
https://gitlab.suse.de/galaxy/testplan

**Comment by Bischoff** [comment]
Again, the test plan is a document used for interlocking and prior planification. It is high level and covers areas to be tested. It is used, if I am not wrong, for interlocking our mission between engineering and QA. Then it becomes kind of "frozen", with an approval process for any change after interlock.

It does not cover individual test scenarios, progress of writing them, or who writes them on an everyday basis. Copying the fast-moving list to  galaxy/galaxy-test-review as announced.

We *might* use that list as an inspiration to derive the 3.2 test plan. But we need an everyday "work in progress" document as well.

**Comment by MalloZup** [comment]
It s a a decision from Klaus. I kind like this, because the team decide, collectively. For everyday we use trello.

**Comment by MalloZup** [comment]
I never saw a definition that the testplan should be less technique. Let make it happens

**Comment by Bischoff** [comment]
I am not even sure the decision is only from Klaus, James is still our QA supervisor, as far as I know, and definition of the test plan is in his hands if I have understood well.

Trello could indeed be an alternative, but it lacks the history that git provides. Our work on manual tests has proved very efficient and traceable thanks to the list in git.

Copied the list to https://gitlab.suse.de/galaxy/galaxy-test-review/blob/master/automation.md . It also has the advantage of grouping all our day-to-day stuff in one place.

**Comment by MalloZup** [comment]
Testplan and test document interlock can be differents. Instead of pointing to managers, we can take initiative to define our structure of the document, so we have no bad surprise

**Comment by Bischoff** [comment]
I was precisely writing to James to let him know about this discussion, and also to raise the issue of writing the testplan for 3.2.

Speaking of the test plan for 3.2, when should that start ? I think we need to define this new test plan document together. This time it will be possible as we are all of us three here (me, Ornela and you) from the beginning. The more eyes the better :-) .

As for "technical document", it was rather a matter of opposing a high level view of the areas to test tothe details of particular Cucumber scenarios. I agree both documents are quite "technical" in essence.

**Comment by kkaempf** [comment]
The SUSE Manager test plan is _explicitly_ _not_ a static document used for interlock (only).

It is a living document, to be adapted on a regular basis.

It is hosted on git on purpose. To be able to tag a state as "interlock" and continue to change the document past interlock.

**Comment by Bischoff** [comment]
I agree test plan is not static, but it has "plan" in it. Let's not mix planing and day to day implementation.

**Comment by Bischoff** [comment]
We need to define new scenarios on a day to day basis. We usually discover them while testing, we add them, we remove them, redefine them and split them. A general set of guidelines cannot be that moving.

How could we achieve such flexibility with a document that needs "two QA engineers and two developers" to be amended (if I read Dario's latest PR :man_facepalming: ) ? (don't misunderstand me, I find it nice that the test plan evolves in a slow and controlled way - but not every day!).

We definitely need a list of areas to be covered by testing, in the test plan. But we don't need to plan for individual cucumber scenarios.

I would even say that we not need to say what is automated and what is tested automatically. For 3.1 we were very happy to switch from manual to automated and from automated to manual, based on practical problems and progress of automation.

Details are implementation, and let's keep implementation separate from planning.

**Comment by MalloZup** [comment]
@Bischoff : 
if you look on the backlog that here were closed, problems are :
- ( this feature were 1 not day to day basis)
- who decided that the feature XX go to automation? 

Take an example from this list:
- test proxy. 

This feature is not detailed in the list.

The testplan should contain like:
```console
test-proxy:
 - create proxy on a trad-client (installation)
 - register a client against proxy
 - register a minion against proxy
 - run cmd etc etc
```
The whole stuff here is not about single cucumber scenario, is a BACKLOG implementation.

We need this with the whole team, because me and you cannot decide alone over the priority and we can miss some features, so we need the help from galaxy.

The testplan should contain all steps the we need to automate.
The technical details where you put them is up to you where you put them.

But this list here were not a day to day list

**Comment by MalloZup** [comment]
""Details are implementation, and let's keep implementation separate from planning.""

We should plan details, because if we implement bad, the plaining was also bad.

**Comment by Bischoff** [comment]
No, details move way too fast. The test plan should be a plan of the areas we cover with testing. These are derived from product definition document, accepted fate entries, and our knowledge of product.

The test plan should not even mention whether manual or automated, we should keep that flexibility. It should not give lists of scenarios to write, lists of manual tests to perform, schedule, assignments to people, prioritization or other day to day management tasks.

Dario, I know from experience we discover a new scenario to write at least once a week. We give up on some scenarios because they are not doable, we did not see problems in the first place. We redefine their scope. All this day to day management can be done on a day to day basis like the rest in https://gitlab.suse.de/galaxy/galaxy-test-review/ while still remaining inside of the scope of what is defined in the test plan.

We can still do adaptations to the test plan if we realize we overlooked entire areas. But det ails of writing the scenarios is a different thing.

**Comment by Bischoff** [comment]
> The testplan should contain like:
> ```console
> test-proxy:
> - create proxy on a trad-client (installation)
> - register a client against proxy
> - register a minion against proxy
> - run cmd etc etc
> ```
> The whole stuff here is not about single cucumber scenario, is a BACKLOG implementation.

Waaay too detailed! And as you say, this is implementation. In the test plan, it is enough to have "we have to test the proxy feature".

BTW, what you describe is what I did in manual-cucumber.md . This file lives with no problem in gitlab so why not the same for automation? (admitting we should go to that level of detail - a TODO is enough for now).

Also, I we must resist the temptation to start big projects and to stop maintaining them afterwards. We must be able to maintain the files on the long run, *sticking to same file structure*. I am volunteering to do this bureaucracy work for automation implementation, like I do it for the manual testing, but the work must remain reasonable, so I am not sure such a level of detail is reasonable and not moving too fast.

**Comment by MalloZup** [comment]
@Bischoff , the whole changes are 

- devs. will comaintain the testsuite. we need a place not QA only, were we discuss stuff.
- we need an agile testplan, that correspond to the reality and it's precise as possible. ( to avoid surprises, that at the end we should mantain) this testplan need collaboration from galaxy not only QA, we lacks on knowledge on specific stuff and so on
- we need less flexibility in a sense if you/me/whatever decide to implement a new test, this test should make sense to maintain and be a needed tests.

We have much more challanges then developing a cucumber scenari

**Comment by Bischoff** [comment]
After a long discussion in private, the immediate backlog will go to https://gitlab.suse.de/galaxy/galaxy-test-review/blob/master/automation.md . The list of product features to test (automated or not) will of course go to the test plan.
