### ISSUE TITLE
Step definitions improvements

### ISSUE THREAD

**Issue by MalloZup** [SUSE/spacewalk-testsuite-base#229]
https://www.relishapp.com/cucumber/cucumber/docs/defining-steps/one-line-step-definitions

**Comment by MalloZup** [comment]
https://www.relishapp.com/cucumber/cucumber/docs/gherkin/scenario-outlines

**Comment by Bischoff** [comment]
I can see above two links, but that doesn't me what the issue really is.

What do you suggest us to do, why, and do you have an example?

**Comment by MalloZup** [comment]
First link show obviously how to create encapsulate methods and class for steps definitions. Tj
Second scenario outline as concrete example take the bootstrap and run command on minions. Within you can refractor and make from 4 features 1. Bootstrap all minions with scenarios.outline

**Comment by Bischoff** [comment]
Thanks for the explanations.

OK for this using classes in steps. This will make ruby code better.

I do not agree with the idea to use scenario outlines for factorizing cucumber text. Gherkin is not a programming language, so the usual idea of factorizing code does not apply. It is not code, it is English. There is no extra cost involved with copying and pasting, but there is a degradation of readability when you use outlines. Outlines should be limited for "sets of examples" (as they are currently used in the test suite), not for factorizing.

Same applies to the "variables" that we started to use, like "sle-minion". It is again reintroduction classical programming structures into Gherkin.

**Comment by MalloZup** [comment]
If gherkin provide scenario outline i do not see problems to use them when they make sense

**Comment by Bischoff** [comment]
Precisely, they make sense for lists of examples, they were never meant for refactoring.

**Comment by MalloZup** [comment]
ok closing
