### ISSUE TITLE
Improve English for feature, scenario and step names

### ISSUE THREAD

**Issue by Bischoff** [SUSE/spacewalk-testsuite-base#241]
Currently, apart from the fact that reading out cucumber features hurts the eyes and the ears, there are many labels that can simply _not be do understood_. While the former problem could be seen as secondary, the latter is a real maintenance and communication problem.

* use proper English
* make sure it is immediately understandable
* use better descriptions:
   * Feature name describe a feature of the product (not of the test)
   * Scenario names describe the test
   * Avoid the obvious like "Check", "Test", "SUSE Manager", etc.
   * Do not detail specifics (user name, package name, etc.) in the scenario names
* use unifying conventions like:
   * Scenario names are sentences based on verbs in imperative form
   * Both feature and scenario names start with a capital letter
   * Avoid parenthesis (painful from command line)

**Comment by MalloZup** [comment]
@Bischoff i"m closing this, since we have a card that you are working on
