### ISSUE TITLE
Make tests idempotent

### ISSUE THREAD

**Issue by Bischoff** [SUSE/spacewalk-testsuite-base#243]
A test should leave the situation "as before" whenever possible. This will:
* reduce the number of dependencies between scenarios
* enable a much more flexible debugging, by running scenarios from command line
(you want to run them in disorder and/or several times)

While we are trying to respect this in every new test we write, there are probably a lot of old tests that are not idempotent.

This would apply at least to cucumber features. If we can achieve it for scenarios too, better, but I don't think this can be a requirement.

**Comment by MalloZup** [comment]
Ok

**Comment by MalloZup** [comment]
@Bischoff we can make this issue in the howtocontribute and close it, what do you think?

**Comment by Bischoff** [comment]
Hmmm, this is a real task to be done.

**Comment by MalloZup** [comment]
@Bischoff  ok for me , we need to target this issue:

i would suggest:
- [ ] First: feature definition:
- define the not idempotent scenario:
 - feature that cannot be idempotent (sync-channels)
 - features that can be reworked and make idempotent

- [ ] Fix non idempotent test.
- [ ] gino_non_idempotent.feature
- [ ] gina2_non_idempotent.feature

**Comment by MalloZup** [comment]
this issue will be adressed, closing
