### ISSUE TITLE
implement function that wait for a "fully" bootstrapped minion, dinamically

### ISSUE THREAD

**Issue by MalloZup** [SUSE/spacewalk-testsuite-base#289]
look here:

https://github.com/SUSE/spacewalk-testsuite-base/blob/master/features/centos_salt.feature#L19

the problem is that at moment all minion we bootrap , do after the bootstrap pkg and hw refresh.

We should wait until  the hardware and pkg refresh are done, sucessefully. In this way we are also 100% sure that we boostrap right a minino at moment the gui doesn't provide this

**Comment by MalloZup** [comment]
this function for more flexibility, should just wait for a list of  named event, via xmlrpc
```console
 wait for success
 	Hardware List Refresh 	
	Package List Refresh 	
        Apply states 
```

**Comment by mcalmer** [comment]
A first try : https://github.com/SUSE/spacewalk-testsuite-base/pull/290
