### ISSUE TITLE
Remove run—testsuite script

### ISSUE THREAD

**Issue by MalloZup** [SUSE/spacewalk-testsuite-base#297]
Historically the script was for exporting vars, but now.we have the env vars in bashrc, so we this script is useless.
We just change dir and run rake
- ensure production (30, 31, head) doesnt run it, check sumaform testrunner in gitlab
- update doc
- remove sumaform code for generation of script

**Comment by MalloZup** [comment]
This is a easy fix task, so some.newbies can take it, to leaern the workflow

**Comment by Bischoff** [comment]
Strongly disagree, for the following reasons:

1 - Syntax with rake is not natural, and is difficult to remember.
2 - We might change the implementation with rake (add options etc) while keeping the run-testsuite command. We could even drop rake completely and call cucumber directly. Have an abstract command like "run-testsuite" makes such implementation changes transparent.

What we can do is remove the variables from run-testsuite command. They are indeed not needed anymore.

**Comment by MalloZup** [comment]
ok, 

convinced only only for 2nd point.

The concept "Natural" in computer Science could require  a philosophy dissertation

**Comment by Bischoff** [comment]
> The concept "Natural" in computer Science could require a philosophy dissertation

True :smile:
