### ISSUE TITLE
REMOVE SMBDA from core-features

### ISSUE THREAD

**Issue by MalloZup** [SUSE/spacewalk-testsuite-base#301]

**Comment by Bischoff** [comment]
@dmaiocchi, please define "core-features" -- I am not sure to understand what this issue is about

**Comment by MalloZup** [comment]
@Bischoff https://github.com/SUSE/spacewalk-testsuite-base/blob/master/run_sets/core-feature.yml#L9

bofh say to me that is not core, so we remove it from the list.

**Comment by MalloZup** [comment]
fixed and adressed
