### ISSUE TITLE
Replace phantomjs with chromium headless

### ISSUE THREAD

**Issue by moio** [SUSE/spacewalk-testsuite-base#314]
Originally opened as a sumaform issue: https://github.com/moio/sumaform/issues/146

**Comment by MalloZup** [comment]
thx @moio @kkaempf , i don't see any hurry for that, since chromium headless is running on beta, and we need absolutely stable test with screenshot.
 we need to wait for this. setting in  longterm milestone

**Comment by moio** [comment]
https://developers.google.com/web/updates/2017/04/headless-chrome is out since some months

Capybara support is also in

We should probably give it a try

**Comment by Bischoff** [comment]
@Mallozup @kkaempf @moio

Well, it might be less efforts to update our phantomjs version first.

Current phantomJS version is 2.1.1 and we are still using 2.0.0, while a version 2.5.0 is in beta state. I have seen changes in the source code that would probably enable us to solve some testsuite problems -- at least the issues where we do not see in phantomJS the changes to the DOM tree. phantomJS is not so much updated anymore, but it is stable, while we might hit all youth problems of a headless chromium.

Of course headless chromium is the long term solution (we would have same browser in testsuite and at users), but I would vote too for not hurrying too much.

**Comment by moio** [comment]
I would go for a quick and dirty test with Chromium. If it looks difficult, phantomjs could be plan B.

Reasoning is: I do not expect big difficulties (but of course can be wrong)

**Comment by MalloZup** [comment]
https://github.com/SUSE/spacewalk-testsuite-base/pull/442

**Comment by MalloZup** [comment]
this is not something that can be done from my side. Afaik this is technical debt.

**Comment by Bischoff** [comment]
@moio what about moving this issue to "galaxy" repo? Let's have issues in only one place.

**Comment by MalloZup** [comment]
Exists already in spacewalk the task. Closing
