### ISSUE TITLE
proposal: yard-cucumber for auto-generation for step and features

### ISSUE THREAD

**Issue by MalloZup** [SUSE/spacewalk-testsuite-base#373]
https://github.com/burtlo/yard-cucumber

this works good and is nice

**Comment by MalloZup** [comment]
**real examples**

![general](https://user-images.githubusercontent.com/10886597/28669253-cbe38e6a-72d3-11e7-95ab-d1011f322b3d.png)
![step](https://user-images.githubusercontent.com/10886597/28669258-d4ae5c5a-72d3-11e7-8ae6-e7076f6af832.png)

**Comment by Bischoff** [comment]
looks nice - much better than the 4 solutions i found during my research...

**Comment by MalloZup** [comment]
@Bischoff thx for you research, i started looking from that

**Comment by MalloZup** [comment]
already tracked in spacewalk
