### ISSUE TITLE
remove lint blacklist from rubocop 

### ISSUE THREAD

**Issue by MalloZup** [SUSE/spacewalk-testsuite-base#379]
this file is genereated by rucocop, it was enerated long time ago, 

```console
rubocop features/step_definitions/*  features/support/* --auto-gen-config 
```

from time to time, we should remove some blacklist

**Comment by MalloZup** [comment]
we need to remove issue blacklisted from here

/bin/spacewalk-testsuite-base$ vi .rubocop_todo.yml

**Comment by ncounter** [comment]
I've started fixing `LineLenght` [here](https://github.com/SUSE/spacewalk-testsuite-base/tree/master-calm-down-rubocop) but it's just in a *WIP* . Feel free to push fixes as soon as you have it to clean up all `rubocop` complaining targets.

**Comment by MalloZup** [comment]
@ncounter can you do a PR with a branch from the upstream project so we can start from your code and commit with you directly?? thx :panda_face:

**Comment by MalloZup** [comment]
technical debt, closing, because there is no community working on the testsuite , so will never be done atm lack of time
