### ISSUE TITLE
Handle modals correctly

### ISSUE THREAD

**Issue by cbbayburt** [SUSE/spacewalk-testsuite-base#437]
We hit race conditions whenever we try to wait on a modal to become visible. This is probably caused by the fade effect.

As a workaround, we are currently operating on the modal without testing if it became visible or not.

Workaround: [Fixed the code to handle modal dialogs](https://github.com/SUSE/spacewalk-testsuite-base/pull/436)

The task is to find a way to correctly wait on a modal to become visible before doing any operation on it.

**Comment by Bischoff** [comment]
Thanks for the issue Can.

One base problem is that phantomjs does not seem to have an updated HTML when animations occur.

**Comment by MalloZup** [comment]
@cbbayburt what is the status of this issue? ( i dont like zombie issues)

**Comment by cbbayburt** [comment]
@MalloZup nothing has been done so far. But this is still relevant. We should open a tech debt issue in spacewalk so we can schedule this in some future sprint.

**Comment by MalloZup** [comment]
@cbbayburt ok thx for feedback.

**Comment by Bischoff** [comment]
@cbbayburt what about moving this issue to "spacewalk" repo? Let's have issues in only one place.

**Comment by MalloZup** [comment]
@Bischoff  i don t think that having issue in one place it is good.

Here we are discussion things, in spacewalk issue are agile cards.

**Comment by Bischoff** [comment]
@dmaiocchi we have "later", "tech-debt" for spacewalk repo.

And this issue could perfectly become an agile task.

**Comment by MalloZup** [comment]
I dont mind. As you wish

**Comment by MalloZup** [comment]
Create a task in spacewalk, it is a good idea
